#!/bin/bash

##############################################################################
# Settings
##############################################################################

# Set this to whatever profile makes the right GPG keys available, from your ~/.m2/settings.xml
export GPG_PROFILE=gpg

# This should be 'release' when really releasing or something else when testing
export RELEASE_BRANCH_PREFIX=release

# Project families that can be released
export VALID_PROJECT_FAMILIES=(kivakit lexakai mesakit)

# We do not release cactus through this script, and its tests take a long time
export CACTUS_TESTS_SKIP=true

##############################################################################
# Check for any arguments (publish, quiet)
##############################################################################

export PUBLISH_RELEASE=false
# shellcheck disable=SC2155
export RELEASE_BRANCH_PREFIX=$(date '+%s')-test-release
unset QUIET
unset SKIP_REVIEW

for argument in "$@"
do
    if [ "$argument" == "publish" ]; then
        export PUBLISH_RELEASE=true
        export RELEASE_BRANCH_PREFIX=release
    fi
    if [ "$argument" == "quiet" ]; then
        export QUIET="--quiet"
    fi
    if [ "$argument" == "skip-review" ]; then
        export SKIP_REVIEW=true
    fi
    if [ "$argument" == "help" ]; then
        echo " "
        echo "release [publish|skip-review|quiet|help]*"
        echo " "
        exit 0
    fi
done



##############################################################################
# Find original workspace (where this script resides)
##############################################################################

# shellcheck disable=SC2046
ORIGINAL_WORKSPACE=$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)

source "${ORIGINAL_WORKSPACE}"/bin/telenav-library-functions



##############################################################################
# Find the previous cactus version (can't build against the current one)
##############################################################################

# shellcheck disable=SC2002
# shellcheck disable=SC2155
export CACTUS_PLUGIN_VERSION=$(cat "${ORIGINAL_WORKSPACE}"/cactus/pom.xml | grep -Eow "<cactus\.previous\.version>(.*?)</cactus\.previous\.version>" | sed -E 's/.*>(.*)<.*/\1/')



##############################################################################
# Determine project families to release
##############################################################################

echo " "
echo "┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┫ Cactus ${CACTUS_PLUGIN_VERSION}"
echo "┋"

read -r -p "┋ What project families do you want to release [kivakit,lexakai,mesakit]? "
if [[ -z "${REPLY}" ]]; then
    export PROJECT_FAMILIES='kivakit,lexakai,mesakit'
else
    export PROJECT_FAMILIES=$REPLY
fi
echo "┋"



##############################################################################
# Determine the release type (major, minor, dot, none) for each family
##############################################################################

MAJOR_REVISION_FAMILIES=()
MINOR_REVISION_FAMILIES=()
DOT_REVISION_FAMILIES=()
NONE_REVISION_FAMILIES=()

for family in ${PROJECT_FAMILIES//,/ }
do
    # shellcheck disable=SC2076
    if [[ " ${VALID_PROJECT_FAMILIES[*]} " =~ " ${family} " ]]; then
        read -r -p "┋    - $family release should be the next (major, minor, dot, none) version or the current version [current]? "
        if [[ -z "${REPLY}" ]]; then
            release_type="none"
        else
            release_type="$REPLY"
        fi
        case $release_type in
        major)
            # shellcheck disable=SC2128
            MAJOR_REVISION_FAMILIES=("$MAJOR_REVISION_FAMILIES $family")
            ;;
        minor)
            # shellcheck disable=SC2128
            MINOR_REVISION_FAMILIES=("$MINOR_REVISION_FAMILIES $family")
            ;;
        dot)
            # shellcheck disable=SC2128
            DOT_REVISION_FAMILIES=("$DOT_REVISION_FAMILIES $family")
            ;;
        none)
            # shellcheck disable=SC2128
            NONE_REVISION_FAMILIES=("$NONE_REVISION_FAMILIES $family")
            ;;
        current)
            # shellcheck disable=SC2128
            NONE_REVISION_FAMILIES=("$NONE_REVISION_FAMILIES $family")
            ;;
        *)
            echo "$release_type is not a valid release type"
            exit 1
        esac
    else
        echo "$family is not a valid project family"
        exit 1
    fi
done

# We need these values to be comma-delimited or we wind up in
# shell-quoting hell constructing maven arguments.

COMMA_SEPARATED_MAJOR_REVISION_FAMILIES=$(echo "${MAJOR_REVISION_FAMILIES[*]}" | tr ' ' ,)
COMMA_SEPARATED_MINOR_REVISION_FAMILIES=$(echo "${MINOR_REVISION_FAMILIES[*]}" | tr ' ' ,)
COMMA_SEPARATED_DOT_REVISION_FAMILIES=$(echo "${DOT_REVISION_FAMILIES[*]}" | tr ' ' ,)
COMMA_SEPARATED_NONE_REVISION_FAMILIES=$(echo "${NONE_REVISION_FAMILIES[*]}" | tr ' ' ,)

echo "┋"
echo "┋ Releasing families: $PROJECT_FAMILIES"
echo "┋ Changing MAJOR revision for [ $COMMA_SEPARATED_MAJOR_REVISION_FAMILIES ]"
echo "┋ Changing MINOR revision for [ $COMMA_SEPARATED_MINOR_REVISION_FAMILIES ]"
echo "┋ Changing MAJOR revision for [ $COMMA_SEPARATED_DOT_REVISION_FAMILIES ]"
echo "┋ Using current version (less any -SNAPSHOT suffix) for [ $COMMA_SEPARATED_NONE_REVISION_FAMILIES ]"
echo "┋"

read -r -p "┋ Does that look correct (yes/no)? [no] "
if [[ "${REPLY}" != "yes" ]]; then
    echo Aborting.
    exit 1
fi


##############################################################################
# Show settings before we start building
##############################################################################

echo "┋"
echo "┋ Quiet: $QUIET"
echo "┋ Publish: ${PUBLISH_RELEASE}"
echo "┋ Project families: ${PROJECT_FAMILIES}"
echo "┋ Release current version: ${NONE_REVISION_FAMILIES[*]}"
echo "┋ Release next minor version: ${MINOR_REVISION_FAMILIES[*]}"
echo "┋ Release next major version: ${MAJOR_REVISION_FAMILIES[*]}"
echo "┋ Original workspace: ${ORIGINAL_WORKSPACE}"
echo "┋ Release branch prefix: ${RELEASE_BRANCH_PREFIX}"
echo "┋ "



##############################################################################
# RELEASE PHASE 0 - Check the workspace to make sure it is ready to be
# released, then clone the develop branch into a temporary workspace,
# whose location we parse from the output of the plugin.
##############################################################################

echo "┋ Installing superpoms"

cd "${ORIGINAL_WORKSPACE}" || exit 1

# shellcheck disable=SC2086
maven $QUIET --no-transfer-progress --batch-mode \
    -Dcactus.version="${CACTUS_PLUGIN_VERSION}" \
    -f telenav-superpom/pom.xml \
        clean install \
        || exit 1

echo "┋ "
echo "┋━━━━━━━ PHASE 0 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓"
echo "┋ Cloning develop branch for release... (this may take a while)"

unset MESAKIT_ASSETS_HOME
unset KIVAKIT_ASSETS_HOME
unset CACTUS_ASSETS_HOME
unset LEXAKAI_ASSETS_HOME
unset CACTUS_HOME
unset KIVAKIT_HOME
unset MESAKIT_HOME
unset LEXAKAI_HOME

output=$(maven \
    -P release-phase-0 \
    -Dcactus.maven.plugin.version="${CACTUS_PLUGIN_VERSION}" \
    -Dcactus.families="${PROJECT_FAMILIES}" \
        validate)

root=$(echo "$output" | grep "checkout-root: ")

if [[ ! $root == *"checkout-root: "* ]]; then
    echo "$output"
    echo " "
    echo "┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┫ ERROR!"
    echo "┋ "
    echo "┋ PHASE 0 - Release checkout failed. Please check your workspace."
    echo "┋ All projects should be on their 'develop' branches with no modified files."
    echo "┋"
    echo "┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo " "
    exit 1
fi

TEMPORARY_WORKSPACE=${root#*checkout-root: }

echo "┋ Temporary workspace: ${TEMPORARY_WORKSPACE}"



##############################################################################
# Create temporary maven repository to ensure a clean build
##############################################################################

export MAVEN_REPOSITORY=/tmp/maven-repository
rm -rf ${MAVEN_REPOSITORY} 1> /dev/null

echo "┋ Maven repository: ${MAVEN_REPOSITORY}"



##############################################################################
# Define Maven JVM options. The system property cactus.release.branch.prefix
# lets us create test release branches without stepping the real release.
##############################################################################

export MAVEN_OPTS="-XX:+UseG1GC \
    -Dcactus.debug=false \
    -DreleasePush=${PUBLISH_RELEASE} \
    -Dmaven.repo.local=${MAVEN_REPOSITORY} \
    --add-opens=java.base/java.util=ALL-UNNAMED \
    --add-opens=java.base/java.lang.reflect=ALL-UNNAMED \
    --add-opens=java.base/java.text=ALL-UNNAMED \
    --add-opens=java.desktop/java.awt.font=ALL-UNNAMED \
    -Dcactus.release.branch.prefix=${RELEASE_BRANCH_PREFIX} ${MAVEN_OPTS}"


##############################################################################
# Check installed tools and clean out project caches
##############################################################################

echo "┋ Removing project caches"
rm -rf ~/.kivakit/
rm -rf ~/.mesakit/



##############################################################################
# Install superpoms and build the workspace without tests enabled
##############################################################################

cd "${TEMPORARY_WORKSPACE}" || exit 1

echo '┋ Installing superpoms'

# shellcheck disable=SC2086
maven $QUIET --no-transfer-progress --batch-mode \
    -Dcactus.maven.plugin.version="${CACTUS_PLUGIN_VERSION}" \
    -f telenav-superpom/pom.xml \
        clean install || exit 1
        
# Temporary hack until we untangle warring DefaultArtifact classes
# from Maven's two versions of its artifact API in Lexakai mojo.
# Just gets it installed ahead of anything trying to use it.
echo "┋ Installing lexakai 1.0.11"

# shellcheck disable=SC2086
maven $QUIET --no-transfer-progress --batch-mode \
    org.apache.maven.plugins:maven-dependency-plugin:3.3.0:get \
    -Dartifact=com.telenav.lexakai:lexakai:1.0.11:jar:app || exit 2


echo '┋ Checking build (no tests)'

# shellcheck disable=SC2086
maven $QUIET --no-transfer-progress --batch-mode \
    -Dcactus.maven.plugin.version="${CACTUS_PLUGIN_VERSION}" \
    -Dmaven.test.skip=true \
        clean install || exit 3 \


echo "┋━━━━━━━ PHASE 0 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛"



##############################################################################
# RELEASE PHASE 1 - Update versions and branch references
##############################################################################

echo "┋ "
echo "┋━━━━━━━ PHASE 1 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓"
echo "┋ Updating versions and branch references"

echo "┋ Changing MAJOR revision for [ $COMMA_SEPARATED_MAJOR_REVISION_FAMILIES ]"
echo "┋ Changing MINOR revision for [ $COMMA_SEPARATED_MINOR_REVISION_FAMILIES ]"
echo "┋ Changing MAJOR revision for [ $COMMA_SEPARATED_DOT_REVISION_FAMILIES ]"
echo "┋ Using current version (less any -SNAPSHOT suffix) for [ $COMMA_SEPARATED_NONE_REVISION_FAMILIES ]"

# Deleteme:  temporary debug stuff
echo "Phase 1 Maven Command-line:"
echo "mvn $QUIET -Dcactus.verbose=true -Dcactus.maven.plugin.version=${CACTUS_PLUGIN_VERSION} -P release-phase-1 -Denforcer.skip=true -Dcactus.scope=family -Dcactus.expected.branch=develop -Dcactus.major.bump.families=${MAJOR_REVISION_FAMILIES[*]} -Dcactus.minor.bump.families=${MINOR_REVISION_FAMILIES[*]} -Dcactus.dot.bump.families=${DOT_REVISION_FAMILIES[*]} -Dcactus.no.bump.families=${NONE_REVISION_FAMILIES[*]} -Dcactus.families=${PROJECT_FAMILIES} -Dcactus.version.flavor.change=to-release -Dcactus.release.branch.prefix=${RELEASE_BRANCH_PREFIX} -Dmaven.test.skip=true clean validate"

# shellcheck disable=SC2086
maven $QUIET --no-transfer-progress --batch-mode \
    -Dcactus.verbose=true \
    -Dcactus.maven.plugin.version=${CACTUS_PLUGIN_VERSION} \
    -P release-phase-1 \
    -Denforcer.skip=true \
    -Dcactus.scope=family \
    -Dcactus.bump-published=true \
    -Dcactus.create.release.branch=true \
    -Dcactus.expected.branch=develop \
    -Dcactus.major.bump.families=${COMMA_SEPARATED_MAJOR_REVISION_FAMILIES} \
    -Dcactus.minor.bump.families=${COMMA_SEPARATED_MINOR_REVISION_FAMILIES} \
    -Dcactus.dot.bump.families=${COMMA_SEPARATED_DOT_REVISION_FAMILIES} \
    -Dcactus.no.bump.families=${COMMA_SEPARATED_NONE_REVISION_FAMILIES} \
    -Dcactus.families=${PROJECT_FAMILIES} \
    -Dcactus.version.flavor.change=to-release \
    -Dcactus.release.branch.prefix=${RELEASE_BRANCH_PREFIX} \
    -Dmaven.test.skip=true com.telenav.cactus:cactus-maven-plugin:${CACTUS_PLUGIN_VERSION}:bump-version || exit 4
        

##############################################################################
# Rebuild everything with tests now that some things have new versions
##############################################################################

echo "┋ Installing superpoms"

# shellcheck disable=SC2086
maven $QUIET --no-transfer-progress --batch-mode \
    -Dcactus.maven.plugin.version=${CACTUS_PLUGIN_VERSION} \
    -f telenav-superpom/pom.xml \
        clean install || exit 5


echo "┋ Ensuring versions are consistent"
# shellcheck disable=SC2086
maven $QUIET --no-transfer-progress --batch-mode \
    -Dcactus.commit-changes=true \
    --no-transfer-progress --batch-mode \
    -Dcactus.scope=all-project-families \
    -Dcactus.include-root=true \
    -Dcactus.scope=family \
    com.telenav.cactus:cactus-maven-plugin:${CACTUS_PLUGIN_VERSION}:homogenize-versions || exit 6


echo "┋ Reinstalling superpoms in case anything was inconsistent"

# shellcheck disable=SC2086
maven $QUIET --no-transfer-progress --batch-mode \
    -Dcactus.maven.plugin.version=${CACTUS_PLUGIN_VERSION} \
    -f telenav-superpom/pom.xml \
        clean install || exit 7

echo "┋ Checking build (tests enabled)"

# shellcheck disable=SC2086
maven $QUIET --no-transfer-progress --batch-mode \
    -Dcactus.maven.plugin.version=${CACTUS_PLUGIN_VERSION} \
        clean install || exit 8


echo "┋━━━━━━━ PHASE 1 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛"



##############################################################################
# RELEASE PHASE 2 - Build documentation
##############################################################################

echo "┋ "
echo "┋━━━━━━━ PHASE 2 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓"
echo "┋ Building documentation"

# shellcheck disable=SC2086
maven $QUIET --no-transfer-progress --batch-mode \
    -P release-phase-2 \
    -Dcactus.maven.plugin.version=${CACTUS_PLUGIN_VERSION} \
    -Dcactus.families=${PROJECT_FAMILIES} \
    -Dcactus.release.branch.prefix=${RELEASE_BRANCH_PREFIX} \
    -Dmaven.test.skip=true \
    -DreleasePush=$PUBLISH_RELEASE \
    -Dcactus.push=$PUBLISH_RELEASE \
        clean \
        install \
        javadoc:javadoc \
        javadoc:aggregate \
        javadoc:jar \
        gpg:sign \
        org.apache.maven.plugins:maven-site-plugin:4.0.0-M1:site \
        verify || exit 9

echo "┗━━━━━━━ PHASE 2 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛"



##############################################################################
# Review the release (unless skip-review is specified)
##############################################################################

if [ ! "$SKIP_REVIEW" == "true" ]; then

    echo " "
    echo "┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┫ Review ┣━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓"
    echo "┋"
    echo "┋ Release is ready for you to review now:"
    echo "┋"
    echo "┋    1. Check the documentation on Github, including links and diagrams"
    echo "┋    2. Check that version numbers and branch names were updated correctly"
    echo "┋"
    echo "┋ The release is in ${TEMPORARY_WORKSPACE}"
    echo "┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛"
    echo " "

    unset REPLY
    while [[ ! "${REPLY}" == "publish" ]]
    do
        read -r -p "When ready to publish to Nexus / OSSRH staging for Maven Central, type 'publish': "
    done

fi



##############################################################################
# RELEASE PHASE 3 - Commit documentation changes, build the release and
# publish to Nexus / OSSRH (https://s01.oss.sonatype.org/)
##############################################################################


echo "┏━━━━━━━ PHASE 3 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓"
echo "┋ Publishing release..."

# shellcheck disable=SC2086
maven $QUIET --no-transfer-progress --batch-mode \
    -P release-phase-3 \
    -Dcactus.verb=Publishing \
    -Dcactus.maven.plugin.version="${CACTUS_PLUGIN_VERSION}" \
    -P ${GPG_PROFILE} \
    -Dcactus.families="${PROJECT_FAMILIES}" \
    -Dcactus.release.branch.prefix="${RELEASE_BRANCH_PREFIX}" \
    -Dmaven.test.skip=true \
        install \
        verify \
        gpg:sign \
        deploy || exit 10
        

echo "┗━━━━━━━ PHASE 3 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛"



##############################################################################
# RELEASE PHASE 4 - Merge changes back to develop and release/current and
# update the develop branch to the next snapshot version
##############################################################################

echo "┏━━━━━━━ PHASE 4 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓"
echo "┋ Merging release and updating to next snapshot version..."

# shellcheck disable=SC2086
maven $QUIET --no-transfer-progress --batch-mode \
    -P release-phase-4 \
    -Dcactus.maven.plugin.version="${CACTUS_PLUGIN_VERSION}" \
    -Dcactus.families="${PROJECT_FAMILIES}" \
    -Dmaven.test.skip=true \
        clean generate-resources || exit 11

echo "┗━━━━━━━ PHASE 4 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛"


# Now pull the changes from all the submodules back into
# the originating checkout, and lastly (so the refs exist),
# those from the submodule root, so the operator does not
# need to get them from the remote.

echo "┏━━━━━━━ PHASE 5 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓"
echo "┋ Updating local checkout from release checkout "

cd "${ORIGINAL_WORKSPACE}" || exit
# shellcheck disable=SC2154
git submodule foreach --recursive git pull "${TEMPORARY_WORKSPACE}"/"${name}"
git pull "${TEMPORARY_WORKSPACE}"

echo "┗━━━━━━━ PHASE 5 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛"


##############################################################################
# END
##############################################################################

echo "┋"
echo "┋ Release of ${PROJECT_FAMILIES} complete!"
echo "┋"
echo "┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
